### ISSUE TITLE
[REQUEST]Would it be possible to update the number of rows without having to restart Firefox?

### ISSUE THREAD

**Issue by GerdchenF** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#102]
Hi,

I find it convenient to work with like 3 tab rows, but from time to time I could use like 15 or 20 rows. For instance at times I want to declutter my tabs and delete several tabs or reorganize them.
It would be really nice if there was a way to set the number of rows which then would take immediate effect.
A really nice way would be if one could grab the lower edge of the tab row container (don't know if it is called container, as I am not that into browser or page design) and just pull it down or push it up in order to increase or decrease the number of rows.

I also don't know if this would be a 10 minutes issue or something like a week's effort, so please excuse me if my suggestion is very difficult or even impossible.

Regards,
Gerd

**Comment by Izheil** [comment]
I checked if I could add it with just CSS using `resize: vertical` along with other things, but it looks like it's going to be a little more complicated than that, since the tab rows would stay at the fixed height after resizing.

Then for some reason I can't get the resizer element childNode from JS, since it's not listed as a childNode, so... the way to go would be making a custom resizer below the tabs bar, which would then be easier to make it work as expected. Sadly I don't have that much time to implement it right now, but I'll update this once I have some more time.

**Comment by Izheil** [comment]
I updated [scrollable multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs) so that now you can resize them.
I couldn't place the resizer below the tabs without creating issues, so I placed the resizer element to the right of them, which should appear next to the scrollbar.

It's disabled by default, so you should go into the script with a code or text editor and change the variable on top named "useResizer" to `true` instead of `false`.

After that, next time you start Firefox you should see that there are 2 small lines to the right of the tabs area. This is the resizer. 
It spans all the height of the tabs, but it's only 10px wide (you can change the width and color of the resizer using the CSS variables below the JS one next to the max number of rows to be used by default).

The CSS max rows variable will still take effect as the "default" max number of rows.

One reason to keep the resizer spanning all the height of the tabs is so that you can make the rows smaller faster by clicking anywhere inside the resizer that is smaller than the actual height of the tab rows.

Being at the right, it also seems to be less intrusive and easier to click than it would have been at the bottom of the tabs area (if we put it at the bottom we'd have needed to make it more than 1px in height to make it convenient to click... which would have displaced the urlbar visibly, etc).

As for the option on the installer, I won't be adding it to the current version, since I'm still working on the new one, and the old is already too cluttered... but it will be a toggleable option in the new. 
You can install it copying the .uc.js file directly from the repo to your [chrome folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Chrome-and-Root-folders#chrome-folder) by now.
