### ISSUE TITLE
Developer Toolbox isn't styled

### ISSUE THREAD

**Issue by awebeer256** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#116]
**Describe the bug**
The browser toolbox is still in light mode.

**To Reproduce**
1. Open the browser to any page.
2. Press `F12`.
3. Get blinded.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: FF87

**Additional information**
Are there some `about:config` changes I've missed? Does this require JS injection?

**Comment by Izheil** [comment]
The toolbar already has a built-in dark mode, so no need to theme it.
Press F12 -> 3 dots button next to the close one -> Settings -> Themes section -> Dark

The reason why the dark theme for the rest of firefox is here is for it's use along with lightweight themes and because the default dark theme of Firefox didn't apply to any about:pages when this was created (and still doesn't for a few ones right now, as found in [this other issue](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/114#issuecomment-809135886)... but at least the most used ones are themed by the default FF built-in one).
