### ISSUE TITLE
[BUG] uBlock Origin's dashboard's cloud sync menu & 'my rules' new additions are hard to read

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#128]
**Describe the bug**
The small menu in the dashboard that allows you to manage UBO's cloud backups has a white background behind its white text, making it very hard to read

**To Reproduce**
1. Install the uBlock Origin theme in addons.css
2. Restart Firefox
3. Open uBlock Origin's dashboard and turn on cloud backups

**Screenshots**
![imagen](https://user-images.githubusercontent.com/71190696/125390307-48a7ea00-e368-11eb-9338-532b82046673.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: FF89.0.2

**Additional information**
More of a sidenote that anything. I'm not a programmer, but would it be possible for you to contribute this upstream? Or is the process just entirely different?

**Comment by Izheil** [comment]
Should be fixed on the [lastest commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/760267827b9482190d5b29f4534c27bb8af01a08) now.

You can redownload the file and change the UUID's, or use the [addons patcher](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/1.1.0) prompting it to redownload the addons file so that it replaces the UUID's for you.

As to push this to upstream, other people tried, and all the related issues seem to be marked as "declined" or didn't get much traction, as can be seen [here](https://github.com/gorhill/uBlock/issues/1869), [here](https://github.com/gorhill/uBlock/issues/204), [here](https://github.com/gorhill/uBlock/issues/3342) or [here](https://github.com/gorhill/uBlock/issues/276), so I think the author is just not interested on implementing it.

**Comment by Elaborendum** [comment]
Thank you! Its dark mode is, sadly, currently only available in the dev builds, and I'll be sticking to the stable release.

**Comment by Elaborendum** [comment]
I don't know if this warrants a separate issue, since this is similar, so I'll just post it here this time around.

![imagen](https://user-images.githubusercontent.com/71190696/125728125-2d8a8da9-c5fa-4dd4-92f9-aa7e6c78bf54.png)

New additions in "my rules" are also light colored on a light background.

**Comment by Izheil** [comment]
Should be fixed now on the lastest release.
