### ISSUE TITLE
NS_ERROR_FILE_NOT_FOUND when importing osfile.jsm

### ISSUE THREAD

**Issue by lmarkus** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#135]
Hello, I'm encountering the following error after updating to 91.0.1 (64-bit)
```
NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import
```

When I get to this line: https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Multirow%20and%20other%20functions/JS%20Loader/root/config.js#L5

Any clues what it might be?

**Comment by Izheil** [comment]
The file it references its a built-in .jsm file inside one of firefox's omni.ja's which allows the use of OS.path for the line next to that (which is why it needs to be imported).

It should be included in all versions of Firefox (at least I just checked on 91 and it is still included).
The issue might have been triggered there when executting the line below, so make sure that the utils folder is in your [chrome folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Chrome-and-Root-folders#chrome-folder) inside your profile folder, and that it has all .jsm files required for it to work.
