### ISSUE TITLE
Multirow tabs scrollable Scrollbar width

### ISSUE THREAD

**Issue by Aushilfsarnie** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#151]
Hello Izheil,
thank you for the great script for multirows.
Is it possible to change the scrollbar width on multirows scrollable when it is set to thin. I want it a little bit larger, but not auto. Thank you

**Comment by Izheil** [comment]
Sadly those are the 3 sizes supported by Firefox using the scrollbar-width property, as can be seen [here](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width).

Although it should be technically possible to overwrite the theming of the scrollbar altogether, but that would affect all scrollbars, since it's impossible to theme just the ones from the tabs scrollbox due to it being inside a shadow-dom, which complicates things.

If you want to overwrite that, you can use [This file, which will show a scrollbar of 12px](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Full%20dark%20theme/Alternative%20scrollbars%20%26%20tooltips/Alternative%20scrollbars/Editable-Scrollbar.css).

**Comment by Aushilfsarnie** [comment]
Thank you very much!
One last thing please: 
"This scrolls down to the current tab when you open a new one, or restore a session." doesn't work at all. Do you have any idea, what is the problem? Thanks!

**Comment by Izheil** [comment]
To me it's working as expected. 

The session restore means built-in one from Firefox, it won't trigger for session-restore extensions.
The easiest way to test it is to open a lot of tabs with Ctr+T repeatedly, and see how the view follows the selected tab (this wouldn't happen with that code).

Same if you close firefox after opening those tabs and restore the session from History > Restore previous session.
