### ISSUE TITLE
[BUG] Multirow Tabs seems not working in 131.0b3 version

### ISSUE THREAD

**Issue by Amarok73** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#153]
As in the title, after update to 131.0b3 Multirows Tabs seems to be no longer working properly. 
Is it something that can be corrected within this mod?

**Comment by Izheil** [comment]
It's already working with the lastest version.
Make sure to remove the old patch and to patch it again, since it was necesary to change both the root folder files, the chrome/utils folder, and the multirow tabs.

After that go to about:support and click the "clear start up cache" button, on the next restart it should be working again.

![preview](https://github.com/user-attachments/assets/d3d4e4a2-9a0c-4bb2-98d6-10554c26f6c9)
