### ISSUE TITLE
optional number of tab rows?

### ISSUE THREAD

**Issue by rschuech** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#29]
Thanks for making this, it was my last resort to get multirows back and it worked!  Would be great to be able to set the number of scrollable rows (currently the max seems to be 2, and I'd like to try 3 or 4).

**Comment by Izheil** [comment]
The reason I set it as 2 max was so that it could scroll while not taking up too much space on top of the browser (thus why I made a compact version with 1.5 rows), but you can set any number of rows by default in the scrollable version changing this rule inside the scrollable multirow file:

<pre>
    #tabbrowser-tabs .arrowscrollbox-scrollbox {
        overflow-x: visible;
        overflow-y: auto;
        display: block;
    	height: calc(var(--tab-min-height)*2)}
</pre>

All you have to change is the <code>*2</code> in there for the number of rows you want (remember that you might need to delete the startupcache when you add new .js files, but it shouldn't be necessary when editing an existing file)
