### ISSUE TITLE
Some tab/link right click options disappeared?

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#32]
Hi Izheil,

I'm using the 06/01/2019 update with Quantum 64.0.2 on Windows 10. 
(Quantum-Nox-Firefox-Dark-Full-Theme-master\Tooltips & Scrollbar customizations\Chrome)

I see that some options such as Move tab to new private window, or Open link on new private window or Open link on new tab/window are not there anymore when right clicking on either tabs or links. How can I get them back?

![](https://i.imgur.com/7V6sjhD.png)
![](https://i.imgur.com/wwLv7iP.png)

Thanks!

**Comment by Izheil** [comment]
Those are only removed when using the "Full theme (except tooltips)" userchrome.css. 
If you only want the colors, use the "Theme colors" files instead.

I'll change the name of the folder, since it seems to cause some confusion... so the "Full theme" should be now "Theme colors + features".

If you still want to use some of the features, instead of using "theme colors" you'll have to edit userchrome.css. To re-enable context menu commands you can find all the context menu commands at the bottom of userchrome.css, after the line that says:  <code>/* CONTEXT MENU COMMANDS */ </code>

The lines you are looking for would be:
 On line 1001:
<pre>/* Move tab */
#context_moveTabOptions,</pre>

On line 1060:
<pre>/* Open link in a new tab */
#context-openlinkintab,
/* Open link in a new window */
#context-openlink,
/* Open link in a new private window */
#context-openlinkprivate,</pre>

**Comment by tungmilan** [comment]
Thank you @Izheil ! I think the right click option Search google for "..." was gone too. I couldn't find it any where?

**Comment by tungmilan** [comment]
@Izheil : I use the files from here
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Theme%20features
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Tooltips%2C%20Scrollbars%20%26%20Multirow%20tabs/Chrome

````

/* Search X on your default search engine *//*
#context-searchselect,

/* Open link in a new tab *//*
#context-openlinkintab,
/* Open link in a new window *//*
#context-openlink,
/* Open link in a new private window *//*
#context-openlinkprivate,
/* Open link commands separator (should only disable if you don't use any of the "open link..." commands) */
#context-sep-open,
````

It did not bring back the context menu that I wanted. What did I miss? Thanks!

**Comment by Izheil** [comment]
You should be using the files from:
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Tooltips%2C%20Scrollbars%20%26%20Multirow%20tabs/Chrome
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Theme%20colors

Not the features folder one.

If you only want the features but not the context menu hidding ones, delete all lines past the one that says <code>/* CONTEXT MENU COMMANDS */</code> (use the search option to find it faster), so that all context menu things are shown.

If you only want to hide one or 2, just check the selector of the one you want to hide in the file, and delete the rest of the selectors.

For example, if you wanted to hide "send image..." but keep everything else, delete all past the line I mentioned, and then add the following rule:
<pre>
#context-sendimage {display: none !important}
</pre>
If you use more than 1 selector, use commas between each one like in the repository.

**Comment by tungmilan** [comment]
@Izheil Thanks. I thought I shouln't use the "Theme color" as I don't want the dark theme?

**Comment by Izheil** [comment]
Ah, I wasn't sure of what things did you want, that's why I mentioned both ways.
Then yes, only use the features one deleting everything after the <code>/* CONTEXT MENU COMMANDS */</code> part.

**Comment by tungmilan** [comment]
Thanks again @Izheil ! Working now
