### ISSUE TITLE
Multirow tabs combined with Tab bar below doesn't work on FF 65 (Win 10)

### ISSUE THREAD

**Issue by TheReptile** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#33]
Today I updated to FF 65 on Win 10. Unfortunately the Tab bar below tweak doesn't work anymore.
I read somewhere the naming of the objects got changed.
Is there any way to fix this?

**Comment by Izheil** [comment]
Multirow tabs works now, just updated it for the stable version (the lines you had to delete were commented for those that were using nightly before for it to work past FF65).

**Comment by TheReptile** [comment]
Yes, I already found that comment in the code and removed it.
This issue is about the Tab bar below tweak doesn't work anymore in combination with the working Multirow tabs.

**Comment by Izheil** [comment]
Sorry, thought you meant that the tab bar was in the wrong position. 
I [updated userchrome](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/c6841eb082cdce851a6bce768cace3b4e2796841) with the tweak, although the title bar seems to be stuck together with the tab bar with the lastest FF update (can't do anything about that with just CSS).

**Comment by TheReptile** [comment]
Hmmm, I tried your suggestion and it sort of seems to work when I use this order:
navbar 1 
personaltoolbar 2
titlebar 3

I have a 3 row tab bar and the webpage overlaps with the 3rd row.

If I change the order to 2, 3, 1 the navbar is below the tabs and then the navbar overlaps with the 3rd row.

I'm using the userChrome.css from Theme features/ and the MultiRowTab-scrollable.uc.js from Tooltips, Scrollbars & Multirow tabs/Multirow scrollable versions/

Of course I cleared the startup cache folder. Any ideas?

I'll try with a clean profile soon.

**Comment by Izheil** [comment]
I can't seem to replicate the problem. When I use the first order you meant (the one of the tweak by default), it works as intended with 3 rows or more, without overlaping over the web area, with the scrollable version and with the regular multirow.

When using the default tab position it still won't overlap and works as intended. The only issue when using the default order when using the tweak is the margin above the tabs (since it was never suposed to be used in the default order) that was left for the urlbar and the bookmarks bar when changed it's order.

I tried asked someone else I know to test the same setup as you, and he doesn't seem to be able to replicate it either (we are both using W10 like you, so that shouldn't be the issue).

Can you screenshot the overlapping? maybe it's some other setting that we may have missed.

**Comment by TheReptile** [comment]
Sorry for the late response. RL took over. But I tried a clean profile and I see no issues there. So I guess my profile got a bit corrupted. Thanks for your time. Now to migrate the important stuff to that.

**Comment by Izheil** [comment]
Ah, thought you just deleted it so I closed the issue. Glad it's working with a clean profile!
