### ISSUE TITLE
After FF65 changes, fullscreen/f11 is not working (win 7)

### ISSUE THREAD

**Issue by gitut2007** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#34]
Hi,
After the FF65 changes, fullscreen/f11 is not working (all it does is the bars move down a little), (also, in userChrome.css: "Tab bar below" you changed prev. version "#TabsToolbar" for "#titlebar" and gave it '3' ( I don' get why would #titlebar be 3 (and anyway it keeps appearing at top if enabled in FF 'customize').

(To have acces to the menu bar in fullscreen/f11 in FF64 I added at the end (a trick I found)): 
/* for alt+f etc to work in fullscreen/moving mouse to the top=menubar appears  */ 
#toolbar-menubar { visibility:visible!important; }
Thanks.

**Comment by Izheil** [comment]
As of FF65, the parent selector for both the tab bar and the menu bar is #titlebar. In previous versions of Firefox #titlebar was the menu bar, but now they changed the selectors, and #titlebar is the parent container of both the menubar (#toolbar-menubar) and the tab bar (#TabsToolbar). 

Since I can only change the order of the same-level elements with "-moz-box-ordinal-group", I used #titlebar to change the position of the tabs (which indirectly also moves the menu bar), since the url bar and the bookmarks bar are on the same level as #titlebar.

In Windows 10 the menu bar appears right above the tab bar (so it would appear between the tab bar and the url bar if you enable the tweak), which is why I wrote the commented out rule below the "tab below" tweak to change the display of the menu bar to be on top for people that wanted it that way. 

As for the fullscreen issue, it seems to happen even with a clean firefox (without any files from here), so that must be yet another "improvement" that came by default with FF65, like the lightweight themes using the text-color specified in them for the tab line for no aparent reason, when until now they had been using the accent-color (which made more sense, since for most personas have white text-color to be able to read the tabs title or the bookmarks text, only using the accent for highlights and the tab line).

Anyway! Thanks for noting the issue, you can fix it with the lastest update of the repository, or just adding this rule anywhere on userchrome.css:

<pre>
/* FULLSCREEN FIX */
/* This will enable the menu bar and bookmarks bar to appear on fullscreen */
#navigator-toolbox[inFullscreen="true"] #toolbar-menubar,
#navigator-toolbox[inFullscreen="true"] #PersonalToolbar[collapsed="false"] {visibility: visible !important}
</pre>

**Comment by gitut2007** [comment]
If no fullscreen at all in FF65 it's done by FF themselves, incredible. 
(I didn't mean that  the menu bar and bookmarks bar were not appearing on fullscreen, but the opposite, all bars remained visible (before this last fix, Idk if it does anything different as without it) all the time no matter if normal or f11, 
while on FF64, on f11 the bars would only appear temporarily if one moved the mouse towards the top, so eg with 150 tabs open, in f11 one would see only one, then move the mouse upwards and click any other tab/a menu bar option/url bar. 
Now the eg 150 tabs (in multirow) and the rest are shown permanently no matter what, eating half the screen 
(the only one that can autohide well with your fix is the bookmarks tab, I tried doing similar autohide code for the other tabs but didn' work well).
Anyway, 
-multirrows/a dark theme
-menu bar/with workable Alt+_ while on f11 
should be standard FF, amazing having to do this appart, they should hire you... 
Thanks.

**Comment by Izheil** [comment]
The fix only made the bookmarks and menu bar showable in fullscreen, F11 already auto-hides the whole navigation toolbox (all the tab bar, url bar and bookmarks bars) IF you have the setting turned on for it.

To turn the setting on, right click an empty space on the tab bar while on fullscreen, and click the "hide tool boxes" setting (if it's turned on it should have a tick symbol next to it).

The only other setting on that context menu is "exit from fullscreen", so you can't miss it.

**Comment by gitut2007** [comment]
Maybe for being w7 FF65 32bit, idk, but here clicking/unclicking that doesn't have any effect. Thanks anyway. FF64 was fine, so hopefully by the time FF66 things would auto-solve, or autohide all becomess possible in normal view, or TabKit resurrects, or something... I don't want to leave FF... so to suffer util them with way decreased screen state. 
Thx.

**Comment by gitut2007** [comment]
It works partially (sadly only on f11, and some bars 'mix' in the same line, menu bar never goes). Idk if besides the new js something else should be in the xml or css. (I delete all files inside the "startupCache" folder before each FF start while trying combinations of settings).
/tab bar below+normal view: no autohide at all, At the top menubar combined with first part of nav-bar, tab bar doesn't show at all; tab bar below+f11: same.
/no tab bar below+normal view : no autohide at all, tab-bar doesn't show at all, tab bar below+f11: partial autohide of nav-bar+part of tab-bar. At the top: menubar doesn't hide, shows combined with first part of tab bar. 
What it's working best now is, based on your 'AUTO-HIDE BOOKMARKS'; I added 
/* AUTO-HIDE titlebar (before TabsToolbar) */
#titlebar {visibility: collapse !important;}
#navigator-toolbox:hover > #titlebar {visibility: visible !important}  
Which works on no-f11 (better), paints a 'ghost' (not clickeable) vertical list of tabs at the left and is finicky to get to the tabs before they disappear, but at least hides the tabs. 
Thanx.

**Comment by gitut2007** [comment]
I tried disabling the addons, then installed FF 65 64bit, same. 
Then I took out the chrome folder, and f11 worked. So I put a fresh chromeuser.css from yor site and f11 worked (previously I had modified the old one by adding/deleting your new changes, and had only changed 2 colors/enabled some context menu commands ). 
I thought I had screwed something before, so I changed the colors etc carefully 1 by one to this new file, opened FF and f 11 worked. 
*I then enabled 'Tab bar below' and f11 stopped working again*. 
So I disabled 'Tab bar below', but f11 kept wrong. *So I thought that chromeuser.css got corrupted if kept open while FF is starting or closing, but weirdly, now f11 got fixed all-of-a-sudden  (while on 'Tab bar below' disabled). 
I repeated all and now I'm sure 'Tab bar below' enabled screws f11, {menubar on top or not}. So I'm just going to leave it 'Tab bar below' disabled.

Anyway I hope al this was not for nothing, the Navigator-toolbox-autohide in normal view would be better than regular f11 autohide, in case you decide to keep implemeting it. 
(Now both 1st and last versions of Navigator-toolbox-autohide.uc.js hide all bars, hover doesn't work, so I had to kill FF with task manager)
Thanks.

**Comment by Izheil** [comment]
Looks like there was some issue with the menu bar when forcing it's position on top that did prevent autohide from applying, so I fixed userchrome to just hide menu bar on fullscreen (as it already did so by default anyway).

If you want autohide with tabs below, I created another version of autohide which should work without this issue. You can check it [here](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Tooltips%2C%20Scrollbars%20%26%20Multirow%20tabs/Other%20experimental%20features) like before.

As for the resized window, I made the hover area to trigger the visible toolbox bigger so that it is easier for it to trigger. If it doesn't trigger for you, try to change the margin-top negative values to something bigger (like -30 instead of -33, etc), since I used the margins that work for me, but they may change a bit on different displays.

**Comment by gitut2007** [comment]
What worked for me {Idk if it matters for this but I use a 4:3 1024x768 monitor}: to give +4pix, so: 
* no-'tabs-below': from your neg 33 41 38 > 29 37 34,  (in addition, Idk if it's right, but I guessed ...'fullscr-toggler'... is the size of the 'hit box' so I augmented from 5pix>15).  In *not needed now f11*: the bars don't show and the hover doesn't work.

The only issue (no problem, I prefer this little loss vs  the advantages of autohide in normal view): I use 'personas plus' and now my background image only is seen 'under' the active tab, the rest under the bars and other tabs is now grey.  Idk if with 'FF color' the same would happen, but from reviews, 'personas plus' is still better, and one can use local files for the background image, 'color' seems to be all online. 

*Now with 'tabs-below' autohide is better than without it*: (same +4pix: 73 81 78 > 69 77 74, same 5>15pix) the reaction to the moving the cursor to the top is faster, and the 'personas' image shows under the menu bar and nav bar, (the tabs bar is the same (image only shows under the active tab)), so a lot more showing of the pic.
(F11 is a little worse: at the left there's the ghost list of tabs and at he right there are permanetly the minimize/close buttons, the rest is the same (the bars don't show and the hover doesn't work) *but it doesn't matter since now f11 is obsolete*).

Can both Navigator-toolbox-autohide-tabs-below.uc.js and Navigator-toolbox-autohide.uc.js be left at the same time as ...js in the Chrome folder? (I am disabling the one I'm not using).

Very cool new function, thank you very much.

**Comment by Izheil** [comment]
If F11 doesn't work, either you need to set more or less margin for the #main-window[sizemode="fullscreen"] #nav-bar element (until you can't see it, but the border should be hoverable).

You can also change the hitbox for the autohide of the non-resized window (you mentioned you changed the resized one, but the non resized is at 1px, which affects maxed and fullscreen).

As for using both files together... Don't. Only use one, or one will override the other, as well as other possible issues arising from it (you don't need to use both anyway).

I'll add a note on the repository about the margins changing depending on the display size for those interested.

**Comment by gitut2007** [comment]
For someone in 1024x768, I have the 3 opts. hover functioning with -69 -68 -70 , (hitbox 1pix ... 5 pix as your original).
Background image didn't work (I disabled personas 1st) Which way should it be? lwt-header-image: ...   
1  url("C:\folder\eg.jpg") !important; 
2  url(C:\folder\eg.jpg) !important;
2  url"C:\folder\eg.jpg" !important; 
3  url C:\folder\eg.jpg !important; 
4 url("file:C:\folder\eg.jpg") !important; 
5 url(file:C:\folder\eg.jpg) !important; 
6 url"file:C:\folder\eg.jpg" !important; 
7 url file:C:\folder\eg.jpg !important; 
For the pic to show well should I make toolbar-bgcolor: rgba(0,0,0,.6) more transparent > toolbar-bgcolor: rgba(0,0,0,.0) ?
Thanks.

**Comment by Izheil** [comment]
None of the above, use:
<code>--lwt-header-image: url("file:///C:\folder\eg.jpg") !important;</code>
... or if you use it from a web link, just copy the link as-is, without the file:///

If you don't want to use the colors part but want to change the header, comment out the other variables while leaving the header ones enabled (they are disabled by default), so it should look like this:
<pre>
:root:-moz-lwtheme {/*
  --toolbar-bgcolor: rgba(0,0,0,.6) !important;
  
  /* You can change the lightweight theme header and footer images with this. 
  To use this, enable the "lightweight themes fix" below. Delete the final /* to use -> */
  --lwt-header-image: url("file:///c:\folder\eg.jpg") !important;
  --lwt-footer-image: url("file:///c:\folder\eg.jpg") !important;

  /* Url and search bars *//*
  --url-and-searchbar-color: #FFF;
  --urlbar-separator-color: #5F6670;
  --lwt-toolbar-field-background-color: rgb(71,71,73) !important}
</pre>

**Comment by gitut2007** [comment]
It works (weird thing, I hadn't noticed that Windows explorer uses ...\...jpg as if were Linux I guess, while FF ulr uses forward slash / which is the one that works here, fortunately you wrote that FF tip...), but same as with Personas; in tabsbar the pic only shows in the active tab, the other tabs are grey. 
Is it  possible to use an image file instead of #main-window {background-color... ? maybe that image would show on the inactive tabs?
Thanks.

**Comment by Izheil** [comment]
<code>--lwt-header-image</code> is the actual variable that firefox uses to change the personas, (if you are going to change the personas with userchrome, don't use personas plus extension, it will cause more problems, and you can already customize all of the toolbar from userchrome.css) so it should change both the active tab and the rest of the toolbar.

If you use #main-window {background: url() !important} to change the background of the toolbar, it will change the background of the toolbar, but not of the active tab.  

If for some reason it's not changing it through the variable mentioned, you can force the change through the persona image selector directly, while making the tabs transparent:
<pre>
:root:-moz-lwtheme[lwtheme-image] {
  background-image: url("file:///C:/Users/Israel/AppData/Roaming/Mozilla/Firefox/Profiles/zpeftoag.default/chrome/Red-galaxy.png") !important;
  background-position: left top !important}

#tabbrowser-tabs:not([movingtab]) > .tabbrowser-tab > 
.tab-stack > .tab-background[selected="true"]:-moz-lwtheme {
  background: transparent !important}
</pre>

**Comment by gitut2007** [comment]
Tried all the sugestions, to no avail.
* Tabs bar, always the unselected tabs keep grey ( I'm using tabs below). 
Actually they go from a dark grey in the more to the left tab to a lighter grey to the more to the right tab,  with eg. the middle tab selected showing a (not transparent, darkened) bit of the persona image. 
Anyway the functional part -autohide- is working very well.

**Comment by Izheil** [comment]
You can't use just any image for the header. They have to be at least your monitor width in pixels and 200px height for it to display correctly. Otherwise the image will get cut somewhere around the middle (since it resizes to fit it's height in the container it's in).

Tabs below would only cause issues if the image was changed from the #navigator-toolbox, 
so if all else fails, you could change both <code>--lw-header-image</code> and <b>#main-window</b> backgrounds, changing both the active tab and the rest separatelly (although there shouldn't be any need for it without personas plus).

For it to work as intended you should be using any lightweight persona that isn't the default ones.

**Comment by gitut2007** [comment]
All my header jpgs are 1024x200 (and were working fine in FF64 {no-tabs below I think}) (when I wrote in prev. post "persona image" I meant just the 1024x200 jpg, no the addon), 
'FF colors' seems not to work with local files, but anyway I have tried your instructions with and without the 'personas addon'. 
I don' have clear if "Tabs below would only cause issues if the image was changed from the #navigator-toolbox," means #main-window {background: url("") !important} */ which in my essays I tried (unselected tabs kept grey so deleted it).
"if all else fails, you could change both --lw-header-image and #main-window backgrounds, changing both the active tab and the rest separatelly" I tried that (I have tried all your previous advices {while on tabs below} and unselected tabs kept grey. 
(Now I have the last code of your previous post but as I said tabs are not transparent but dark grey to light grey from left to right).
"you should be using any lightweight persona that isn't the default ones" 
If that means the 'themes' that appear in FF 'customize', I have tried your suggestions with ligh, dark, default, different Victoria secret's....

**Comment by Izheil** [comment]
Try with a clean userchrome from this repository, and just change <code>--lw-header-image</code>.
It's working for me with tabs below enabled from the autohider, so I'm not sure why isn't it working for you, unless there is something else interfering.

That variable just tells firefox that the lightweight theme you are using has the background image you specify, so it really shouldn't cause any issue at all.

**Comment by gitut2007** [comment]
I put fresh versions of your latest files, and now unselected tabs are transparent, selected tab partially transparent, url bar partially transparent, menu bar transparent, all show the jpg. 
I think the problem before might have been this code: 
/* This changes the menu bar on top of the screen intead of over the tab bar */... if enabled (*seems to be unnecessary/redundant*);
* Previously I enabled it (uncommented it) when using 'tabs below', now following your advice, I only changed 2 (3) things: 1 enabled and put lwt-header-image, and 2 enabled 'tabs below' (plus 3 'margin to 40px if you want to use the menu bar on top' instead of 10)
Now anyway the menu appears bar 'on top of the screen instead of over the tab bar' even though that code is disabled and I'm with tabs below.

* So now the jpg fixed, but a semi-new issue (was happening only in f11 -since now innecessary I didn't care-), now on normal view too): an unclickeable ghost vertical list of all tabs appears at the left when the toolbar hides. When one hovers and the tabs appear, the list disappear.
It's a not so terrible thing and I prefer that the jpg shows.

**Comment by Izheil** [comment]
You don't have to enable tabs below on userchrome if you are using the tabs below version of autohide, since the changes will get overriden by the JS file rules.

Try the new autohide file, it makes the whole navigator bar dissapear, no need to adjust margins now. It should avoid any further issues with random thing appearing on screen.

As for the background of the urlbar, making it transparent would only show the navigator toolbox background (which is white by default or dark using userchrome from here), and applying opacity to the parent elements gets inherited to the child elements, so... no, not possible.

**Comment by gitut2007** [comment]
The background of the urlbar is already semi-transparent and when one hovers over the addons icons those squares become even more transparent, so I thought maybe there was some parameter to adjust that, but no problem, not important., 

I'm using all the new versions of the files (I thought the ghost column had something to do with sidebar, so I tried disabling Sync-tabs-sidebar.as but no effect), including the new autohide file, yes I noticed no neeed to adjust margins, more elegant and is working great.

The  *unclickeable ghost vertical list of all tabs that appears at the left when the toolbar hides* makes difficult to read a bit only on some web pages that show content from the very left, so only slightly annoying. On web pages with a wider margin it's actually kind of usefull to see the list of tabs, they also show the moving dot while the tabs load (I use a lot 'open link in new tab' -that you curiously have hided by default in right click menu- many times from the page I'm in). 
(I thought the vertical list maybe was a 'feature' made by you on purpose since you use a wider screen).

So if I manage to make it go I'll inform you, otherwise no problem, I'm fine with how things are working now.
Thank you.

**Comment by Izheil** [comment]
There is no line of my code that makes the urlbar nor the addon icons become transparent on hover, autohide just makes them dissapear, so I don't think I can help with that.

As for the unclickable vertical list of all tabs... oddly enough, on W10 the bookmarks appeared in the same manner, which is why I hid them on the file, but when trying it on W7, it happens with the tabs as you said. I fixed it with the last update, so that shouldn't happen anymore.

As for the 'open link in new tab' hidden by default, you can already manage the same effect clicking links with the wheel on your mouse, or with the combination of keys <code>Ctrl</code> + <code>Left mouse button</code>, so I deemed that option redundant.

In either case, I understand that everyone uses Firefox in different ways. For some tabs should go below (thus why the tabs below fix), and for others that looks horrible, which is why I tried to make it easier for people to install the basic coloring, without the CSS tweaks, since they will have different ways of using Firefox than my own, and as for those that do use the CSS tweaks, I tried to only hide the things that you can already manage with other faster combination of keys, or that are overall rarely used (like send image, which is more times misclicked than how many people actually use it, since when you are going to send a message with an image, it's more common to just open the messaging page/program of your choice to make a planned message than just sending some file on the go).

Anyway, glad that it's already working for the most of it (and hopefully the last update will fix the ghost tabs).

**Comment by gitut2007** [comment]
Ghost gone, thxs (*and even though f11 is working too, I won't even use it anymore*);  all is ✓ now. The Mozilla people should take a look at this theme.
Many thanks.
