### ISSUE TITLE
 Is this compatible with 'Firefox Color' and 'Firefox side-view' experimental features?

### ISSUE THREAD

**Issue by gitut2007** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#35]
Hi, is this compatible with
 https://testpilot.firefox.com/experiments/color  https://color.firefox.com/ 
https://testpilot.firefox.com/experiments/side-view 
Thanks.

**Comment by Izheil** [comment]
The color theme shows an overlay color over the colors I set for the theme, so yes, it is compatible, although they will look darker. 
If you intend to make a light theme with it you won't be able to use the colors part of this theme (although you shouldn't be using a dark theme with a light theme addon in the first place, so... yeah)

About the sideview, it works as intended, but the context menu and the default empty "test page" of the side view won't be themed, since it's an external addon.
