### ISSUE TITLE
Current tab offset up

### ISSUE THREAD

**Issue by Lim4multirowtab** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#38]
Hi Izheil,
Thanks to you and to the other members of the team for this nice job.
I have installed the version 01-02-19 (FF65) which was working well, except bottom tabs were wider than the on above rows.
The last version (03-02-19) fixes that small issue, but then the current tab (whatever the row), offsets slightly to the tab which make the whole row a little bit more "tall".
Also, every row seems a bit with more height to me (maybe I am wrong), however, I don't find where to decrease the height of all tabs, if ever possible. Could you tell me where to find it? I am not a developer but I can find my way (at least I hope).
Thanks again,
Lim.

**Comment by Izheil** [comment]
Which version of firefox  and OS are you using? Since they seem to change the tab selectors on Firefox 66 again, the issue you mentioned happened there. There also seems to be some differences on windows 10 and older windows versions.

If on FF65 stable, are you using the scrolling version, or the infinite rows one?

**Comment by Lim4multirowtab** [comment]
So I use FF65 stable on Win10 x64.
Yes I put your files (and only yours, but onlyMultiRowTabLiteforFxFF67.uc.js, userChrome.css and userChrome.xml ) in chrome folder.

So I managed to reduce the height of rows, except for when when one tab of the row is active and except for the last row where the + (Open a new tab) keeps this little offset up and then push the whole slightly down.

In fact to be more precise, any active tab and the + (Open a new tab), create some pixel above which push the whole row slightly down and create a little gap.
This did not exist on previous file of 01-02-2019.

![row gap](https://user-images.githubusercontent.com/47348157/52338328-8976d880-2a23-11e9-99e3-ef108b366397.jpg)

See the difference between top row with an active tab, bottom row with the + pushing slightly up, and he middle row which has a normal gap.

**Comment by Izheil** [comment]
If you are using stable version you should be using MultiRowTabLiteforFx.uc.js, not the FF67 versions, since the FF67 one uses the different selectors introduced on FF66+ (so it would not work right with FF65). You will only need to use the FF67 versions once firefox updates to FF66+.

I'll specify it better in the readme.

**Comment by Lim4multirowtab** [comment]
All good now for this little gap or offset issue.
You are right, I thought that MultiRowTabLiteforFxFF67.uc.js was good for FF65 and already prepared for the next Firefox releases.

Regarding the fix width of the bottom tabs, yes this is exactly what I wish to have and it was working that way with MultiRowTabLiteforFxFF67.uc.js and not anymore with MultiRowTabLiteforFx.uc.js.
So I will try the change you propose.

And finally regarding this multirow tabs subject, I managed to reduce the height of the tabs o 20px which reduces every rows and give more space for the main window for websites.

Also, I appreciate your dark theme very much and I can see the great and huge work (even if I don't understand everything...).
Perhpas a little thing could be done regarding the selection, for example, of the content of the URL bar. The dark background becomes full whit when selecting the URL. Perhaps this could be darker es it is the only full white item displayed. In fact , this white background in other places, but I can't remember where exactly.

Thank very much again for your nice work and kind help.

Lim.

**Comment by Lim4multirowtab** [comment]
All good now for this little gap or offset issue.
You are right, I thought that MultiRowTabLiteforFxFF67.uc.js was good for FF65 and already prepared for the next Firefox releases.

Regarding the fix width of the bottom tabs, yes this is exactly what I wish to have and it was working that way with MultiRowTabLiteforFxFF67.uc.js and not anymore with MultiRowTabLiteforFx.uc.js.
So I will try the change you propose.

And finally regarding this multirow tabs subject, I managed to reduce the height of the tabs o 20px which reduces every rows and give more space for the main window for websites.

Also, I appreciate your dark theme very much and I can see the great and huge work (even if I don't understand everything...).
Perhpas a little thing could be done regarding the selection, for example, of the content of the URL bar. The dark background becomes full whit when selecting the URL. Perhaps this could be darker es it is the only full white item displayed. In fact , this white background in other places, but I can't remember where exactly.

Thank very much again for your nice work and kind help.

Lim.

**Comment by Izheil** [comment]
I just updated userchrome and usercontent so that you can now change the background and text color of selected text on the url bar and on <code>about:</code> pages. They will be bluish by default now.

In userchrome you can now change the colors changing the hex values of this rule (it is located below both the :root rules in the updated version):
<pre>
/* Highlight color on browser windows (url bar, library, search box, bookmarks properties...) */
#urlbar *|*::selection, .searchbar-textbox *|*::selection, #infoBox *|*::selection, 
#editBMPanel_namePicker *|*::selection, #editBMPanel_tagsField *|*::selection,
#editBMPanel_tagsSelector *|*::selection, #placesToolbar *|*::selection,
#mainDeck *|*::selection, dialog *|*::selection, #certDetails *|*::selection,
#SignonViewerDialog *|*::selection, #CookiesDialog *|*::selection {
  /* This is the background color */
  background: #a22 !important;
  /* This is the text color */
  color: #fff !important}
</pre>

As for usercontent (for the <code>about:</code> pages), you can change the highlight colors using the 
<code>--highlight-on-selection-bg</code> and <code>--highlight-on-selection-text variables</code> inside it.

**Comment by Lim4multirowtab** [comment]
Sorry for my late answer Izheil, I was a bit busy these last days.

So I changed the userChrome.css and it works perfectly. I use #666666 and #d9d9d9 and it looks fine for me.

I haven't change usercontent as I have not put in the Chrome folder yet. In fact, I don't see what it is for compared to userChrome. And because, I don't know coding, I try to make all this as simple as possible for my very little knowledge.

Thank you again for your kind help !

**Comment by Izheil** [comment]
Usercontent changes the <code>about:</code> pages of firefox, such as the preferences page, or addons page, and even some firefox support pages that couldn't be themed otherwise.

You don't really need it if you are okay with those pages being white.

Userchrome only changes the browser windows, such as the navigator toolbox (where the url bar is, etc), or some dialog windows, but it won't affect things inside the websites viewing area.

**Comment by Lim4multirowtab** [comment]
Clear explanations ! All understood. Thanks 👍

**Comment by Lim4multirowtab** [comment]
> 
> 
> So I use FF65 stable on Win10 x64.
> Yes I put your files (and only yours, but onlyMultiRowTabLiteforFxFF67.uc.js, userChrome.css and userChrome.xml ) in chrome folder.
> 
> So I managed to reduce the height of rows, except for when one tab of the row is active and except for the last row where the + on the far right (Open a new tab) keeps this little offset up and then push the whole row slightly down.
> 
> In fact to be more precise, any active tab and the + (Open a new tab), create some pixel above which push the whole row slightly down and create a little gap.
> This did not exist with your previous file of 01-02-2019.
> 
> ![row gap](https://user-images.githubusercontent.com/47348157/52338328-8976d880-2a23-11e9-99e3-ef108b366397.jpg)
> 
> See the difference between top row with an active tab, bottom row with the + pushing slightly up, and he middle row which has a normal gap.

Hi Izheil,
So after updating to FF66 using the last MultiRowTabLiteforFxFF66.uc.js file, I can see a little gap between the last rows (out of 4) wherever the current tab is.
And current tab is selected on other rows, there is a slight movement down of the whole row. It's a bit light that there would not be enough space for the little line that enhances the selected tab.

Not sure to be clear, but I can try to explain in different ways if you don't understand what I mean...
