### ISSUE TITLE
Debian ESR Firefox 60.5 eBay Buttons

### ISSUE THREAD

**Issue by DebSec** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#43]
I'm having issues for some time now with buttons occasionally on eBay and sites I come across sporadically. Some of the buttons on eBay have a white background until hovered on or executed and then they turn blue. There code is messed up as they have been using new code in some areas and the old coded buttons still work. The search is one button and send in private messages and a few others.

https://imgur.com/a/3UmsvQX

**Comment by Izheil** [comment]
The search button looks blue without hover and on hover for me, just like the private messages. None of my code affects pages apart from <code>about:</code> sites, at most, it used to affect some textareas that use <code>about:blank</code> like the one you mentioned in previous issues, but since I already deleted the <code>about:blank</code>, not even those would get affected now.

This may have to do with the changes you did to the checkboxes file.

Have you tried without usercontent (which is the only that could really affect those sites)?

**Comment by DebSec** [comment]
@Izheil ,
You are correct. I was lazy and did not proof out my additions. 

It was some css code I was pulling in from : 
https://github.com/MrOtherGuy/firefox-csshacks/blob/master/content/limit_css_data_leak.css

All seems fine now. Thanks for bearing with me.
