### ISSUE TITLE
Doesn't work any longer with tabs below navbar

### ISSUE THREAD

**Issue by bukephalos** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#44]
Before Firefox 65 it was enough to add these lines to get all the toolbars into their natural order:
#nav-bar {-moz-box-ordinal-group: 1 !important}
#PersonalToolbar {-moz-box-ordinal-group: 2 !important}
#TabsToolbar {-moz-box-ordinal-group: 3 !important}

and best of all it worked with your multi-line-tabs-solution.

For Firefox 65 there are new -- much more complicated -- solutions on the net to order the bars but I couldn't manage to combine them flawlessly with your code. Main problem: the top of the web page is hidden by the tabs. And some further customizations get overridden (less important, I think I can fix these with some trial and error)

So my wish is to have some optional code (js or css) to move the multi-line tabbar below the navbar with minimal impact on other customizations I have done.

**Comment by Izheil** [comment]
I already have the updated selectors for that on the CSS tweaks userchrome. It works with multi-row and doesn't hide the top of the web page.

Make sure you are using the updated version:
<pre>
/* TABS */

/* Tab bar below (You can set the order of each bar here. 1 for top, and 3 bottom) */

/* #nav-bar is the ID for the URL bar, #PersonalToolbar the ID for the bookmarks bar, and
#TabsToolbar should be self-explanatory (The tabs on bottom are already set by default here) */

/* Don't change the #navigator-toolbox margin unless you want more margin on top */

#nav-bar {-moz-box-ordinal-group: 2 !important}
#PersonalToolbar {-moz-box-ordinal-group: 1 !important}
#titlebar {-moz-box-ordinal-group: 3 !important}

#navigator-toolbox {margin-top: 10px !important}
/* ^ Change the margin to 40px if you want to use the menu bar on top ^ */
/* This changes the menu bar on top of the screen intead of over the tab bar */
/*
#toolbar-menubar {
  position: fixed !important; 
  width: 100% !important;
  top: 0px !important;
  margin-top: 7px !important;}

#toolbar-menubar .titlebar-buttonbox-container {
  float: right !important}

#main-window[sizemode="fullscreen"] #toolbar-menubar {display: none !important}
#main-window:not([sizemode="fullscreen"]) #toolbar-menubar {display: block !important}
/* ^ There seems to be an issue with the "top: 0" rule inside #toolbar-menubar that would not allow fullscreen
to autohide, so it's safest to just hide it on fullscreen */
</pre>

The only difference from the code you have is that you have to change #TabsToolbar for #titlebar due to how Firefox 65 structured the navigator tab.

If you want to have the menu bar (tool bar where the archive, file, etc) on top of it all, you will also have to enable the rules below (just delete the /* that comes above the #toolbar-menubar selector, AND change the margin-top of #navigator-toolbox from 10px to 40px (so that part of the urlbar or the bookmarks bar doesn't get eaten on top of the screen). Otherwise, it will just appear above the tabs bar, but below the other toolbars.

**Comment by bukephalos** [comment]
Thanks. I didn't use your userchrome, only the js.
With your userchrome.css it works somehow but with two gaps in the layout.
One above the tabs and the other above the last tabs row.
The first gap is only visible as long as Firefox is in full screen mode. It goes away as soon as the window is resized.
The second gap goes away aus soon as I remove the "add new tab" button (the "+" after the last tab)
I tried to attach a screenshot but I am not sure if github has got it, at least I cannot see it while writing this comment

**Comment by Izheil** [comment]
The only time when that happens is if you are using any of the FF66 versions on FF65 instead of the regular multi-row ones, or the other way around.

If you are using Firefox 65, don't use the FF66 compatibility ones.
So if you want to use non scrollable multirow for example and you are using Firefox 65, use <code>MultiRowTabLiteforFx.uc.js</code>, not <code>MultiRowTabLiteforFxF66.uc.js</code>.

The F66 files are only needed for nightly and beta releases.

**Comment by TheReptile** [comment]
@Izheil 3 days ago you pushed this change: https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/a908e76b618940c7ba7d720be3297159dd8a920e 
The change in CSS tweaks/userChrome.css on line 50 also breaks the tabs below navbar.
I reverted that change locally and everything works again.

**Comment by Izheil** [comment]
Looks like I forgot a ":not" in there, it should be fixed now.
