### ISSUE TITLE
Bookmarks Library not Dark

### ISSUE THREAD

**Issue by Octagoncito** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#45]
The bookmarks library isn't dark. Mine is white.
chrome://browser/content/places/places.xul
Any way to have a dark background for this?

**Comment by Izheil** [comment]
I updated the theme so that now it's dark when opening it from a link (such as bookmarks).
You can check the fix [here](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/ba171695e68f9d03d9bd2effa1c921620537cf55). 
You only need to replace <code>usercontent.css</code> with the updated one.

**Comment by Octagoncito** [comment]
Thanks!
