### ISSUE TITLE
[REQUEST]... and Solution for tabs width and height

### ISSUE THREAD

**Issue by Lim4multirowtab** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#48]
Apologies to Izheil to have messed up his _Issues_ threads.

So for those who would like to change the width and the height of the tabs, here are some possibilities that seem to work well without introducing new problems (this is just what I found, I am not a coder).

- Width (thanks to PaddlesAU)
In `MultiRowTabLiteforFx.uc.js`:
`.tabbrowser-tab:not([pinned]) {
        /* flex-grow:1;       /* replaced with next line for fixed size tabs */
        flex: 0 0 70px;
        min-width: 70px important!}`

- Height
In `userChrome.css`:
`#tabbrowser-tabs {
  --tab-min-height: 20px !important;
  margin-left: 0px !important;
  height: 20px !important;
}`

**Comment by Izheil** [comment]
I'm sorry to see that you have taken personally that I locked the other thread.

You were asking for a fix to change the height, while the issue had to do with closed tabs being registered on Tab Session Manager, even after I had warned you to start a new issue if you had a different problem.

The reason to have issue threads is to keep track of single issues, so that other people with similar ones can see how it was solved. 

Either way, I'd recommend you to learn CSS so that you can apply any custom fixes without having to depend on other people next time. 

W3C has good tutorials on the matter:
https://www.w3schools.com/css/default.asp

**Comment by Lim4multirowtab** [comment]
No, no sincerely Izheil, I didn't take it personally at all.
You were absolutely right to say what to you said. Absolutely no problem for me.
I just tried to find a way to report the solutions I have found to my questions that may interested others, but without mentioning an issue as it is not an issue at all. Moreover, my requests were not related to your work which I greatly appreciate.

You are right when you want to properly organize this reporting system offered by github, but as it is not exactly a forum, I was not sure if I could open a new topic for subject that are not directly related to your coding.

My apologies was sincere. :)
