### ISSUE TITLE
MultiRowTab MinWidth

### ISSUE THREAD

**Issue by 532910** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#49]
IIRC, mltirow tabs with firefox 65 has respected `browser.tabs.tabMinWidth` firefox setting.

And now, on firefox 66, I've modified `--min-tab-width` in `MultiRowTabLiteforFx.uc.js`.

Is it possible to redefine `--min-tab-width` outside `MultiRowTabLiteforFx.uc.js` and not modify `MultiRowTabLiteforFx.uc.js`?

But it will be better to use `browser.tabs.tabMinWidth` for `--min-tab-width`.

**Comment by Izheil** [comment]
Some people complained about not being able to modify the width of tabs (I assume they didn't know about the <code>about:config</code> setting), which is why that variable was defined inside the file in the last update.

Either way, I'll add where the setting is in <code>about:config</code> and remove it from the multirow file for a safer approach for the next versions.

All you need is to change the min-width property from <code>.tabbrowser-tab</code> selector so that it only keeps <code>flex-grow</code>:
<pre>
    .tabbrowser-tab:not([pinned]) {
        flex-grow: var(--tab-growth)}
</pre>

**Comment by 532910** [comment]
I believe that, people who don't  know about `about:config`, don't know how to use MultiRowTab scripts.
Thank you!
