### ISSUE TITLE
PortableApps support

### ISSUE THREAD

**Issue by lucknaumann** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#57]
Hi and thanks a ton for this!
I was wondering if there's a way to use this with the PortableApps FF or if there are plans to do so.

**Comment by Izheil** [comment]
There is support for it, the instructions were already on the releases page. The reason why it doesn't appear as an entry in the installer is because I can't predict where people will place it inside their computer.

Pasted from the releases page:

<h2>Firefox portable</h2>

If you are using Firefox Portable, you will need to change the default "Root" and "Profile" paths to the ones of wherever you placed Firefox Portable.
For example, if you placed it in <code>C:\FirefoxPortable</code>, and you are using a 64-bits version, you will have to change the paths to look like:

Firefox:
 - Root: <code>C:\FirefoxPortable\App\Firefox64</code> <- For 32 bits, just remove the 64
 - Profile: <code>C:\FirefoxPortable\Data\Profile</code>

**Comment by lucknaumann** [comment]
Thanks! Yeah, that makes sense not to have it in the installer. I thought I might have seen the instructions or mention of it somewhere before but couldn't find it. Obviously didn't think to check the releases page (Duh!) =)
