### ISSUE TITLE
No MultiRow tabs

### ISSUE THREAD

**Issue by Traveler4** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#61]
**Describe the bug**
Though following the documentation thoroughly, tabs do not appear in muliple rows.

**To Reproduce**
I did a virgin installation of FirefoxPortable 75.0 (64bit) into the folder IF ("Installation Folder").
I switched `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`.
I checked `about:profiles` to find my profile folder => PF.

I downloaded the files from [this repository](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme) and copied
* `Multirow and other functions\JS Loader\root\config.js` 	to  `IF\config.js`
* `Multirow and other functions\JS Loader\root\defaults\` 	to   `IF\defaults\`
* `Multirow and other functions\JS Loader\utils\`                   to `PF\chrome\utils\`
* `Multirow and other functions\Multirow tabs\MultiRowTabLiteforFx.uc.js` to `PF\chrome\MultiRowTabLiteforFx.uc.js`
	
Startet FF, but tabs did not appear in multiple rows.

I did the same with an installed version of FF (68.7.0esr (64-Bit)), but without success => 
==> Tabs do not appear in multiple rows.

**Expected behavior**
Tabs should appear in multiple rows.

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Win10 Version 1909, Build 18363.778
 - Version: [FF75.0 Portable](https://portableapps.com/de/apps/internet/firefox_portable) and [FF68.7.0esr (64-Bit)](https://www.mozilla.org/de/firefox/all/#product-desktop-esr)

**Additional information**
not applicable

**Comment by Izheil** [comment]
`toolkit.legacyUserProfileCustomizations.stylesheets` should only be necessary for userChrome.css and userContent.css.
Make sure your installation folder for Firefox portable follows this structure as stated in the patcher description:

> If you are using Firefox Portable, you will need to change the default "Root" and "Profile" paths to the ones of wherever you placed Firefox Portable.
For example, if you placed it in <code>C:\FirefoxPortable</code>, and you are using a 64-bits version, you will have to change the paths to look like:

> Firefox:
>  - Root: <code>C:\FirefoxPortable\App\Firefox64</code> <- For 32 bits, just remove the 64
>  - Profile: <code>C:\FirefoxPortable\Data\Profile</code>

Since you were using the manual method, the profile should also have the chrome folder inside it where you will place your functions and the utils folder (as you described you already did, so that shouldn't be the issue).

So following the previous example, placement of the files of the root folder should look like:

```
C:\FirefoxPortable\App\Firefox64\defaults\pref\config-prefs.js
C:\FirefoxPortable\App\Firefox64\config.js
```

**Comment by Traveler4** [comment]
Yep, that was my mistake! On FF Portable I put the files into `C:\FirefoxPortable` and not into `C:\FirefoxPortable\App\Firefox64` ! Now it works like a charm, great!

Still not successful though with the FF68.7.0esr (64-Bit), but I will postpone further investigations until they are going to release a new version.

Thankyou for the help and the great functional added value to Firefox browsing!

Ah, perhaps one question more: is there anything that can be done against this waste of screenspace? 
![image](https://user-images.githubusercontent.com/52359342/80797274-b3289c00-8ba1-11ea-8efc-1dc5e4b78e58.png)

**Comment by Izheil** [comment]
Current multirow doesn't work on anything lower than FF70, so you will have to use an [old version of multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/f98b8ab363a8b287aed2e78bed7c1fa58314b081/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTabLiteforFx.uc.js) or [old scrollable multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/f98b8ab363a8b287aed2e78bed7c1fa58314b081/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTab-scrollable.uc.js) from the repo for ESR, although I'm not sure how well it will do, since I'm not too familiar with ESR.

As for the wasted space, it actually belongs to the min/max/close buttons container, which holds the flexbox of the tabs visible (if we just make the min/max/close buttons have a fixed height, the tabs will overlap the address bar).
The other alternative would be show those buttons above the tabs box, which would overlap a few tabs, which wouldn't be desirable either...
It's also not possible to move those buttons inside the tab bar because it would then keep moving along with the tabs... so as far as I know, it can't be done easily (might be possible, but I'm not sure on how)

**Comment by Traveler4** [comment]
OK, "at least FF70" explains it well.

Thanks for the explanation on the wasted space. It would be possibly best if the min/max/close buttons could be arranged vertically instead of horizontally (or even changing between horizontally and vertically, whenever the other arrangement would waste fewer screenspace). But it's not Windows standard of course and I can imagine that it is hence difficult (to impossible) to realise unless the whole application window would use skins like in the screenshots below (just less ugly ones ;-) ). Never mind - having back the tabs in multiple rows is great enough! 
![grafik](https://user-images.githubusercontent.com/52359342/80801803-cb061d00-8bad-11ea-905a-7b04697baa65.png) ![grafik](https://user-images.githubusercontent.com/52359342/80801553-1d930980-8bad-11ea-9756-b853417b270d.png)

**Comment by Izheil** [comment]
Lol, well, the problem with vertical buttons is that they would start as vertical (thus you'd always have at least 3 rows open, even if you only had 1 tab), but I'll look into possible fixes for that space.

I won't make any wild promises since it might take a while until I figure out something (if I manage to), and right now I don't have as much free time because of studies, but I'll re-open this if I ever have good news about it.
