### ISSUE TITLE
[BUG] Multi row tabs stopped working on Mac FF 76.0

### ISSUE THREAD

**Issue by RealSkeptic** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#63]
**Describe the bug**
After restarting Mac, multi row tabs, which previously worked, stopped working. The tabs display horizontally. 

**To Reproduce**
* Install patch in FF 76 (release) at root folder
* Copy utils to profile folder / chrome
* Copy `MultiRowTab-scrollable-autohide.uc.js` to profile folder / chrome
* Restart FF

**Expected behavior**
Tabs should appear in multiple rows

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version FF76.0

**Additional information**

* I changed `--tab-growth` to 0. The tabs in FF display at fixed width, but in one row.
* I tried reinstalling the patch manually and restarting FF. It did not help. I tried installing through the python script and restarting FF. Also did not help.

**Comment by Izheil** [comment]
Since Mac doesn't currently have an official installer, and the python script depends on some modules that need to be pre-installed, and Mac being "special" on what to allow... it's better to go manual by now, at least until I rewrite the installer.

I just tested on scrollable autohide Mac on FF76, and it's working for me:
![Mac](https://user-images.githubusercontent.com/33794458/81356449-7c86e000-90d1-11ea-81d4-238c82543486.png)

You mentioned changing `--tab-growth` did change the tabs width, so the script seems to be getting registered at least, so it doesn't seem likely that the files are in the wrong folders.

Did you use `MultiRowTab-scrollable-autohide.uc.js` from the [installers](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Installers/functions) path, or the one from [Multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs) folder?

The one from the installer gets changed by the installer after patching (or at least, should), so you should use the [Multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs) path one when installing manually.

Apart from that, you could try deleting the contents of `startupCache` folder before restarting firefox just in case.
It's located in the local profile directory (so `about:profiles` -> open local profile directory), and should should be inside a hidden folder by default (you will need to use `cmd + shift + .` to show it after accesing the local profile directory). It has a few `.bin` files inside, most of them starting with `scriptCache-`.

**Comment by RealSkeptic** [comment]
Thank you for responding, but unfortunately, it doesn't work.

I copied `MultiRowTab-scrollable-autohide.uc.js` from the `Multirow tabs` directory. This time I didn't even change it for `--tab-growth`, but the result was the same. I think the tab size is fixed because that's the FF default, not because it actually loads anything.

Clearing the script cache files also didn't help (restarted FF after that). 

Is there any way for me to know if it loaded the file or not? I tried adding some `console.log` lines but they did not show (I'm not a Javascript expert).

**Comment by Izheil** [comment]
If the `--tab-growth` didn't change anything then it most likely didn't register the script.
The easiest way to test this is to copy [this test file](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Other%20features/Test.as.css) to your chrome folder. If it gets registered you should see red borders around every element in Firefox interface (it will be hard to miss). If you don't see any change, then the files aren't being read at all.

Make sure that the contents of the [root folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader/root) from the repo are inside `/Applications/Firefox.app/Contents/resources`, so that the 2 files in there are placed in these locations:

```
/Applications/Firefox.app/Contents/resources/config.js
/Applications/Firefox.app/Contents/resources/defaults/pref/config-prefs.js
```

There should be another file inside `/Applications/Firefox.app/Contents/resources/defaults/pref` folder named `channel-prefs.js`, make sure to NOT delete it.

For your profile folder, you can access it through `about:profiles` root directory section (there should be a button to open the location). Once in there, find the chrome folder, which should be somewhere in:
```
/Users/(Your-login-username)/Library/Application Support/Firefox/Profiles/(profile folder)/chrome
```
The utils folder should be there, and the .uc.js files outside (directly inside the chrome folder).

So the structure should be something like:
```
/Users/(Your-login-username)/Library/Application Support/Firefox/Profiles/(profile folder)/chrome/utils/(all the .jsm files here along with chrome.manifest)
/Users/(Your-login-username)/Library/Application Support/Firefox/Profiles/(profile folder)/chrome/MultiRowTab-scrollable-autohide.uc.js
```

Also make sure to either clone the repository, or download the raw version of the files you need (some people did a ctrl+a when in the file overview, copying the header of the page, which would render the files useless.... so yeah)

Your firefox might have deleted one of the root files, like `/Applications/Firefox.app/Contents/resources/defaults/pref/config-prefs.js` upon update, so you should check the root folder files first.

**Comment by RealSkeptic** [comment]
I tried that and the test css worked (everything was covered with red boxes).

I then decided to try some debugging, and found how to use `console.log` correctly.

As it turns out, the script throws an exception on this line:

```javascript
if (document.querySelector("#tabbrowser-tabs .tabbrowser-arrowscrollbox").shadowRoot) {
```

The exception's message is

```
document.querySelector(...) is null
```

Could it be that you can't recreate this because you have some other CSS loaded which causes this not to be null, which I don't? `MultiRowTab-scrollable-autohide.uc.js` is the only function I use, I don't even have a `userChrome.css`.

**Comment by Izheil** [comment]
In the test I was using only `MultiRowTab-scrollable-autohide.uc.js`, and CSS can't add elements (of which the selectors would point to), nor do I add any new element on the other JS files.

Also... the `#tabbrowser-tabs .tabbrowser-arrowscrollbox` selector is an old one from [previous versions](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/FF75/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTab-scrollable-autohide.uc.js) (seems to be the one from the FF75 branch), not from [the current one](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTab-scrollable-autohide.uc.js), so I guess that was the issue.

Try getting the [updated one from the master branch](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTab-scrollable-autohide.uc.js) (You might have gotten redirected to the FF75 branch from the releases page when clicking the releases title, and then it kept redirecting you to that branch if you were using a history link to get to the repo).

**Comment by RealSkeptic** [comment]
OK. That did the trick. Indeed, I was using the latest one from the releases page, I didn't realize it was not the actual latest one.

**Comment by Izheil** [comment]
Yeah, sorry, in the script it said it was compatible with FF76 (which was the current nightly at the time it was tested), so it was easy to not notice.

I'll make sure to ask for the version used in new bugs and link to the newest version directly next time.
