### ISSUE TITLE
[BUG] Multirow-Patcher-Quantum-Nox-Installer-Linux not permanent

### ISSUE THREAD

**Issue by thomas-maeder** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#67]
**Describe the bug**
The modifications applied by Multirow-Patcher-Quantum-Nox-Installer-Linux work perfectly, if Firefox is started immediately after running Multirow-Patcher-Quantum-Nox-Installer-Linux but not permanently.

In particular, after having switched to a different Linux user and back, I have to run Multirow-Patcher-Quantum-Nox-Installer-Linux again or I end up with a single row.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Start Firefox - there is only one row of tabs
2. Stop Firefox
3. Apply Multirow-Patcher-Quantum-Nox-Installer-Linux
4. Start Firefox - tabs are in multiple rows
5. Stop Firefox
6. Log out
7. Log in as different user and repeat steps 1 to 6
8. Log in as intial user
9. Start Firefox - there is only one row of tabs

**Expected behavior**
I expect to have to run Multirow-Patcher-Quantum-Nox-Installer-Linux once per Firefox profile.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Version Firefox 76.0 (current stable)

**Comment by Izheil** [comment]
Should be fixed now.

The main problem was that I changed the owner from root to the current logged in user after copying the files (since they are created as root for having to run the executable with elevated privileges), which would allow the user to execute the files only in the current logged in user.

When sharing the same Firefox profile with different users in the same computer, the privileges of the patch files would remain only available for the owner that created them (since I didn't change the privileges). Now all users should have read and execute privileges (so changes will be seen in other users that run the same patched profile), but only the owner group should be able to modify the files.

**Comment by thomas-maeder** [comment]
Thanks.

I have tried Multirow-Patcher-Quantum-Nox-Installer-Linux-v1-5-5.

I get this output:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "Builder.py", line 749, in patchInstall
  File "Builder.py", line 284, in fullPatcher`

**Comment by Izheil** [comment]
Yep, sorry, just noticed now that I made the wrong import in the last fix, should be alright now.

**Comment by thomas-maeder** [comment]
Thanks. And don't be sorry.
The error message has disappeared.
I am not usually switching between users at the weekend, so give me some time to test.

**Comment by thomas-maeder** [comment]
> I am not usually switching between users at the weekend, so give me some time to test.

The weekend is over, and I have switched users quite a few times without losing the patch.

Multirow-Patcher-Quantum-Nox-Installer-Linux-v1-5-6 works like it should.

Thanks again!
