### ISSUE TITLE
[BUG] "The path Not found was incorrect."

### ISSUE THREAD

**Issue by emulated24** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#68]
**Describe the bug**
On macOS Catalina 10.15.4 I call the installation script and after it asks for credentials, it throws an error: "The path Not found was incorrect."
Using Python 3.7.7. 

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Download the full zip of the package from github.
2. Run commandline and execute: python3 Quantum-Nox-Installer.py

**Expected behavior**
Popup windows to appear allowing Multirow patch.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Browser: Firefox 76

**Additional information**
This was working fine before on this computer. I'm not sure what has changed in the package or in Firefox.

**Comment by Izheil** [comment]
Try running with sudo, since otherwise the elevated privileges from console don't seem to get read correctly on Mac for some reason.
```
sudo python3 Quantum-Nox-Installer.py
```

If it doesn't show correctly, see what paths is it getting by default with this:

```
sudo python3 Quantum-Nox-Installer.py --print-defaults
```

**Comment by emulated24** [comment]
Hi Izheil,
I have downloaded the latest version.
This is the outcome:

```
tool:Installers miso$ python3 Quantum-Nox-Installer.py
sudo: setrlimit(RLIMIT_STACK): Invalid argument
Password:
sudo: setrlimit(RLIMIT_STACK): Invalid argument
The path Not found was incorrect.
```

When trying to print out the path as you suggested, nothing comes out:

```
tool:Installers miso$ python3 Quantum-Nox-Installer.py --print-defaults
sudo: setrlimit(RLIMIT_STACK): Invalid argument
sudo: setrlimit(RLIMIT_STACK): Invalid argument
The path Not found was incorrect.
```

Any suggestions please?

Thanks,
Miso

**Comment by Izheil** [comment]
Looks like it [might be a problem with your version of `sudo`](https://github.com/sudo-project/sudo/issues/8), which might have gotten some wrong update after Catalina 10.15.3... which explains why it was working correctly before, but not after you updated.
Check your version of Sudo with this (caps are important):
```
sudo -V
```
If it's anything lower than 1.8.31, you should [update it](https://www.sudo.ws/download.html#binary) (the `.pkg` binaries for Mac are in the second table in that page, midway through the page).

After updating, it will give you some of the first warnings (before it re-runs as root), but it should run as it should after the password prompt.

To check if it was updated correctly restart the terminal and run the previous version check command again.

I tested on Catalina 10.15.0, which was unaffected (older versions of sudo didn't have the issue), which is probably why it ran good for me without giving any warning.

If updating doesn't work, try with:

```
sudo -s python3 Quantum-Nox-installer.py
```
... which should elevate the console before running the script, instead of just running the script as elevated user.

**Comment by emulated24** [comment]
Okay, I updated sudo to latest version:

`tool:Installers miso$ sudo -V
Sudo version 1.9.0
Sudoers policy plugin version 1.9.0
Sudoers file grammar version 47
Sudoers I/O plugin version 1.9.0`

Still the same problem with the path though:
`tool:Installers miso$ sudo python3 Quantum-Nox-Installer.py

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
The path Not found was incorrect.`

Even when calling with -s switch:
`tool:Installers miso$ sudo -s python3 Quantum-Nox-installer.py
The path Not found was incorrect.`

What am I doing wrong...
Something to do with the Firefox profile perhaps?

**Comment by Izheil** [comment]
You aren't doing anything wrong, don't worry.

The patcher is just not finding the profile folder for some reason and is exiting since it can't find a correct folder. Sometimes this can happen if using custom paths, custom named profiles, or secondary accounts.

I thought it might have been an issue with sudo command, and thus the patcher not having enough privileges to even read the root folder, but it looks like that wasn't it.

I updated the patcher now so that it won't exit if it doesn't find any path (I forgot to prevent that from happening if not using the command line arguments), so hopefully now you should be able to at least open the patcher window and then select the paths if they aren't found.

Although I'm not sure why they aren't found... Did you place Firefox installation somewhere else than the applications folder or renamed it?

If what it's not finding is the "root" folder, you'll have to specify it once it opens... it should be something like:
```
/Applications/Firefox.app/Contents/resources
```
If it's the profile folder, you can find the path in `about:support`.

**Comment by emulated24** [comment]
You're the man! That made the trick.

Yes, I am using custom profile name. That's why the script got confused.
All good now, I selected my profile manually, patched, et voila, multirow.
Thanks Izheil, much appreciated.
