### ISSUE TITLE
How to change how many tabs in multi rows?[BUG]

### ISSUE THREAD

**Issue by forplan0** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#69]
I just install your multi row addon and i am not happy with number of tabs in one row...

Now i have 18 tabs in row and then firefox made new row...

How to set this to may. 10 tabs in row?

Regards

**Comment by Izheil** [comment]
That isn't controlled by the script, but you can control it changing the minium width of tabs in `about:config`.

Search for `browser.tabs.tabMinWidth`, click the pencil icon, and set a bigger value in there. By default it's 76px, so try any value higher than that but below 226 (which is the maxium size of tabs when no other tab is open).

For me at 160 it displays 10 tabs in a row, but my screen display holds up to 23 tabs in a row, so it will probably be lower for you... since you can test in `about:config` without restarting the browser after each change you can live-test until it has as many tabs as you like.

**Comment by forplan0** [comment]
Thank you very much!  I set to proper number.
