### ISSUE TITLE
[REQUEST] Umatrix and Forget Me Not Addon Support

### ISSUE THREAD

**Issue by Rayqan** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#70]
Would it be possible to create additional addon themes for the Umatrix and Forget Me Not addons? As always thanks for your great work.

**Comment by Izheil** [comment]
Just to confirm, you mean these 2, right?
* [uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/)
* [Forget Me Not](https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/)
I can do themes for them, but since I don't use them myself, I won't activelly update them (Kinda like no-script addon), so if the addon developers change the design (like uBlock recently, althought I use that one) you'll need to request an update for them each time that happens, since I won't know.

(Although seeing Forget Me Not more closely, it covers some functionability that I had from different addons, so I might use it later on)

**Comment by Izheil** [comment]
Well, I just added a dark theme for both of them.
You can check it [here](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/1084bc4491c63610e02377313cc8e5fc767ce65d), or directly in the [`addons.css`](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Full%20dark%20theme/addons.css) file.

**Comment by Rayqan** [comment]
Sorry for not responding earlier, both themes work perfectly and I will make sure to request an update if needed. Thanks again for all your work.
