### ISSUE TITLE
not quite a [BUG] - A tiny issue in Full dark theme/addons.css

### ISSUE THREAD

**Issue by roie-r** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#72]
A tiny issue in **Full dark theme/addons.css**
The UUID place-holder for **Noscript** appears as [TYPE-UUID-OF-NOSCRIPT-ADDON-HERE], then at line 577 as [TYPE-UUID-OF-NOSCRIPT-HERE] - so you can't grab them all as once.
Other than that - great theme :)

**Comment by Izheil** [comment]
Thanks for using it!

The reason why it's like that is because the first section refers to the common internal parts, while the other section applies to the popup (with some rules overlapping the first section rules, so they have to be apart). 

Although I agree that automating the UUID string replacing would be a good addition. 

I think it shouldn't be too tedious to make a string replacer with python getting the UUID strings from `addons.json` file in the profile folder and then replacing the placeholders in the addons that each person has installed. I'll see if I can get it going without a GUI (since to just replace some placeholders it shouldn't be needed) reusing some parts of the installer that is already available for the functions.

When I have more time later on I'll see if I can port it to a batch script, which should be more portable.

**Comment by roie-r** [comment]
I think you missed what I meant - just that the place-holder at line 577 isn't the same as the previous three (missing the word ADDON)... it's minor.
Automating the euuid replacement would be nice, I already have a little script to do that. Also for some reason addons.json doesn't have all the UUIDs (at least in my installation), you'll need to get them elsewhere.

**Comment by Izheil** [comment]
Well, I unified the naming convention for the placeholders for the new automation script, so that should be solved now.
As you mentioned I ended up getting the UUID's from somewhere else, although I first thought they would be there.
I placed the script on the [theme folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Full%20dark%20theme).

**Comment by roie-r** [comment]
That great. Thanx.
