### ISSUE TITLE
[REQUEST]  Multirow Tab Height

### ISSUE THREAD

**Issue by Ryushin** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#73]
Please add the option in the patch tool to set the height of tabs when using Multirow tabs.  
I add "--tab-min-height: 20px !important;" to MultiRowTabLiteforFx.uc.js

Diff:
```
@@ -43,12 +43,14 @@ function zzzz_MultiRowTabLite() {
         Value of 0 -> Tab doesn't grow. Uses tab min width as fixed width. */
 
     :root {
-        --tab-growth: 1}
+        --tab-growth: 1;
+       --tab-min-height: 20px !important;
+       }}
 
     .tabbrowser-tab:not([pinned]) {
         flex-grow: var(--tab-growth)}
         
-    .tabbrowser-tab::after {border: none !important}
+    .tabbrowser-tab::after {border: true !important}
 
     :root:-moz-lwtheme[lwtheme-image] {background-repeat: repeat-y !important}
```

**Comment by Izheil** [comment]
I [added the option to change the tab height in the script now](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/dcaf71f5bb2f24a35d55756d8ff05b676010ccfe), which you can fetch from [here](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTabLiteforFx.uc.js) (Just right click > Save as...), but after testing some values on the height variable, there are a few reasons why I won't be exposing the option in the patcher:

* The minium height that it register is 29px, which is the minium height to avoid clipping content inside the tab (which is why 29px is the height already used by compact mode). Even if you change the value to 20px or lower, it will default back to 29px (that is unless you started changing fonts and the size of every element in the tab to allow a lower height, which is out of the scope of multi-row tabs, and would be best done as a standalone thing).
* Since the only reason to change the height of tabs inside the script would be to make the tabs BIGGER instead of smaller (and I don't think the "touch" density is that small to need it), it's not likely that many people using the script will be using touch screens to need such a thing... it will just seem like a bloated option to add to the patcher.
* I don't think I could place it anywhere inside the multi-row tabs section that wouldn't lead to confusion on which version does it apply (at least in the current patcher).

With that said, if you want to get the same result as your script, just enable compact mode inside the customization panel (right click empty space in tab bar -> Customize/personalize -> Density button -> Compact mode), which you can change on-the-go without the need to restart the browser.

For that to take effect make sure that your `--tab-min-height` in your fix doesn't have a specific value (you can only make it inherit the value set by density if you place it anywhere else than on `:root`, like on the change I linked).

The only use-case I can see in this is if you didn't want to enable compact mode for any reason?
