### ISSUE TITLE
[REQUEST] Mac Instalation Script for patcher.

### ISSUE THREAD

**Issue by lensam69** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#81]
**Is your feature request related to a problem? Please describe.**
Installing the theme for Mac is usually a manual affair. 

**Describe the solution you'd like**
Have an installation script that would place all files in the right folders

**Describe alternatives you've considered**
None

**Additional context**
I'm happy to volunteer my time to write this feature if you feel it's a good addition to this repo. If not, feel free to close the feature request.

**Comment by lensam69** [comment]
Closing. Seems I misinterpreted how the patcher works :)

**Comment by Izheil** [comment]
Well, if you meant the actual theming part (userChrome.css/userContent.css) and not multirow/etc ... yeah, it doesn't have an installer right now.

I have planned to add it (or something more flexible) in the new installer, which will manage scripts better using something like a "mod manager" to avoid having to redownload the files with each update.

I'm posting [the progress so far](https://ko-fi.com/Blog/Post/Extension-development-D1D7221P5) on my [ko-fi](https://ko-fi.com/quantum_nox) page.

The main reason why I didn't want to add the theming part to the old installer was because I think the theme needs a few improvements (right now it's good enough, but it could be better), as well as it being intended more as a template for people to adapt to their uses than to use as is.

The other reason is that for the first install it will be fine by just appending if userChrome.css exists, but on update we'd have to parse the part where we appended the file, leave the variables untouched, and update any new rules. This would be fine to do if I never added any new variable... which isn't the case (and then I'd have to check for which version of the theme they had to parse things correctly... which would be hard to mantain).
