### ISSUE TITLE
Unable to get MultiRow to work in Firefox 80.0.1 Portable, but other uc.js scripts work fine

### ISSUE THREAD

**Issue by albino1** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#84]
This isn't a bug or a feature request, more of a support request, so I removed the template.  I hope that's okay.

I've been using `MultiRowTabLiteforFx.uc.js` for quite some time, but I paused my updates at Firefox 70 since everything was working great.  Now I want to make the upgrade to Firefox 80, so I grabbed [a portable version](https://portableapps.com/apps/internet/firefox_portable) to test with (80.0.1), but I'm unable to get `MultiRowTabLiteforFx.uc.js` to work with it.

I'm using [the latest version](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTabLiteforFx.uc.js) of the MultiRow script (`Firefox 70 to Firefox 82.0a1 (2020-09-06)`) along with the the [JS Loader method](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader) and then eventually tried Methods 2 and 3 from the [CustomJSforFx](https://github.com/Aris-t2/CustomJSforFx/) repository.

Regardless of which method I use, MultiRow tabs don't show up even if I just CTRL+T a bunch of them on a completely fresh profile.  To make sure there was nothing wrong with how I did things with JS Loader, I added both `Bookmarks-Toggle.uc.js` and `Focus-tab-on-hover.uc.js` and both of those work correctly, but still no MultiRow.

I've tried installing several more fresh portable versions, deleting the `startupCache`, and switching install methods, but no luck with any of those.  Bookmarks Toggle, Focus Tab, and various CustomJSforFx scripts all work, but not MultiRow.

I feel like I must be missing something obvious since it's always worked in Firefox 70 and below, and I've used the portable version to test with in the past before upgrading my actual main profile install, though I suppose it could be related to using a portable version.  Any advice would be appreciated, thanks!

**Comment by Izheil** [comment]
I just tested `MultiRowTabLiteforFx.uc.js` on the lastest portable version from the same page you linked and it seems to work alright for me.

Make sure you didn't accidentally remove the "uc." part from the extension, otherwise it would not get loaded at all (so if you renamed it to something like `Multirow-tabs.js` it wouldn't get loaded, but it would if it was `Multirow-tabs.uc.js`.

Just in case I'll go over the basics so that you can check that everything is where it should:

Let's asume for eample that you placed portable firefox directly on C:\

1. Place the "defaults" folder (as a whole) and "config.js" file (both inside the "root" folder in the JS loader section of the repo) directly into `C:\FirefoxPortable\App\Firefox64` (that is if you have a 64-bits system, otherwise, place it on `C:\FirefoxPortable\App\Firefox` instead).
2. Place the "utils" folder (from the repo) into `C:\FirefoxPortable\Data\profile\chrome`.
3. Place `MultiRowTabLiteforFx.uc.js` from [here](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow and other functions/Multirow tabs/MultiRowTabLiteforFx.uc.js) in `C:\FirefoxPortable\Data\profile\chrome` as well.

The startupCache folder in portable firefox is in `C:\FirefoxPortable\Data\profile\startupCache\` (by default portable firefox `about:profiles` will only show the actual non-portable firefox profiles that you may have.

Alternatively try using the [installer](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases), changing the paths correspondingly for FF portable.

**Comment by albino1** [comment]
Thanks for the reply!

I deleted everything, rebooted, and then did it over from scratch, all prepared to start giving you screenshots and a video showing it not working, but then it worked... go figure.  I'm sure it was user error on my part, but I honestly have no idea what I was doing wrong.  I double then triple checked with your post and it all lined up, and voila this time it worked.

I appreciate the help, thank you.
