### ISSUE TITLE
[REQUEST] More Context Menu Items

### ISSUE THREAD

**Issue by jingofett** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#88]
https://privatebin.net/?977a0798edd8931c#6zpHYfF9PYe2y6uEkz2vAhpTbkhQ5c85qYE4vTUDPSL4

All of these can be used under the webarea context menu section of the context-menu-commands.as.css file

**Comment by Izheil** [comment]
To me all those elements are useful and shouldn't be hidden (except the individual navigation buttons, which I just hide altogether), which is why I didn't add them, but I [added them now](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/e4d7df6bfe750bb49b62e080543b0d808e1833d1) for people to hide regardless.

Apart from the ones in there, I also added most other context menu items (I might have missed a few), so you can now hide almost anything if you want, including all separators, copy/paste elements, view source, etc...

They are also now divided by their action, so that they are easier to find.
