### ISSUE TITLE
[REQUEST] Multirow support under Content

### ISSUE THREAD

**Issue by Kassenschlager** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#89]
Hello, 

thanks for your theme, can't  work without it. Is there any chance to add the option to move the multirow tabbar to the bottom of the screen under the web-content? Last thing i am missing from Tab Mix Plus.

Greetings

**Comment by Izheil** [comment]
I just made some script for that, you can get it [here](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Other%20features/Tabs-on-bottom.uc.js), or from the [`Multirow and other functions/Other features`](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Other%20features) folder from the repo.

I won't be adding it to the current installer because I'm phasing it out in the near future, but you can just place that file in your [chrome folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Chrome-and-Root-folders) after patching your Firefox with the current installer, and it will get recognized regardless (although if you are using the theme I assume you already know where that is).

The `Tabs-on-bottom.uc.js` file has one setting, which is showing the min/max/close buttons when not in fullscreen, or keeping them hidden (they will show regardless of that choice in fullscreen) at the top of the script, but by default they will be hidden (I assume that just like with `tabs-below*.uc.js` files, people will want to keep the menu bar enabled for those buttons).

**Comment by Kassenschlager** [comment]
Thanks a bunch, i can finally say that i don't miss the legacy firefox addons anymore.

**Comment by Izheil** [comment]
Glad to help!

**Comment by Izheil** [comment]
@Kassenschlager, A small heads up on a small fix!
I just realized a small issue on fullscreen while using multirow, where having more than 1 row it would not hide all tabs...
I fixed it now, so re-download it for the fixed version!

**Comment by Kassenschlager** [comment]
A question, is there a way to always hide all tabs on fullscreen. The mouseover function makes it impossible to control the youtube player in fullscreen for example.

**Comment by Izheil** [comment]
I just updated the file. 
By default now the tabs will be hidden on fullscreen (unless you change a variable at the top of the script to return the old behaviour) until you press `shift + t`, which will show them temporally.

You can change the keys combination to use for that inside the script as well.
