### ISSUE TITLE
[REQUEST] about:blocked should have red background

### ISSUE THREAD

**Issue by tycho** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#92]
**Is your feature request related to a problem? Please describe.**
When visiting a site that's flagged as dangerous by the Google Safe Browsing API, the background right now is the grey one provided by Quantum Nox.

**Describe the solution you'd like**
It would be ideal if the page was as noticeably alarming as it is with the default Firefox styles (`--in-content-page-background` of `#A4000F`).

I'm not sure how to implement it. Right now Quantum Nox sets `--in-content-page-background` to `#202020` with `!important` globally. It seems like one way to handle it would be to do something special for `@-moz-document url-prefix(about:blocked)`, but I'm not sure about the precedence of two CSS rules with `!important`, etc.

**Describe alternatives you've considered**
Could use the default Firefox interface styles, I guess, but they're awful.

**Additional context**

With Quantum Nox right now:
![2020-10-20_08-16](https://user-images.githubusercontent.com/29616/96606840-90ec1d00-12ac-11eb-92c9-ebcc5e010397.png)

Default theme:
![2020-10-20_08-22](https://user-images.githubusercontent.com/29616/96607712-7bc3be00-12ad-11eb-80fb-5ac2c8f1b601.png)

**Comment by Izheil** [comment]
Thanks for the heads up!
It should be fixed now.
You can test it using the test page at [http://testsafebrowsing.appspot.com/s/malware.html](http://testsafebrowsing.appspot.com/s/malware.html).

I chose a less bright red `#550000`, which should still alert people of the state of the site without being too eye-straining, so that it now looks like this:

![Blocked site color](https://user-images.githubusercontent.com/33794458/96651937-267fbf00-1336-11eb-95cf-ab7965c10691.png)
