### ISSUE TITLE
[Request] Theme on secondary profiles

### ISSUE THREAD

**Issue by tugl** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#93]
Under `about:profiles` you can have multiple Firefox profiles, but I'm unable to apply this theme for secondary profiles. The .css files are copied to the new `chrome` folder, but they don't get loaded.

Would there be a way to have this theme working on secondary profiles?

**Comment by Izheil** [comment]
By default the patcher only copies the required files to Firefox root folder (to load the JS and other CSS files) and to the default profile folder (that copies the functions).

If you are using the patcher to copy the .css files, select the profiles you want to copy the files in the "Profiles only" section after having patched your firefox installation.

This means that you have to first "patch" your used firefox installation (you can untick all functions in the patcher for this step), and click the "patch" button.
Once that's done (if you have already patched the default profile before you already did that), you only need to select the "Profiles only" section and highlight the other profiles you want to patch, with the functions you want to patch from the right section.

If you instead mean the `userChrome.css` and `userContent.css` files don't get loaded, make sure that you have toggled `toolkit.legacyUserProfileCustomizations.stylesheets` in about:config to `true` in those other profiles, otherwise they won't get loaded.

**Comment by tugl** [comment]
Thanks, I forgot to mention I already had legacy style sheets enabled for both profiles, the patcher also patched both profiles, but only the default one gets themed. 

Are you able to reproduce a new profile with your theme enabled on it?

**Comment by Izheil** [comment]
Yes, I just tested it, and it applies correctly to both my default profile and the newly created one using the patcher.

Try checking if the files are actually in the [chrome folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Chrome-and-Root-folders#chrome-folder) of the profile where it doesn't work. Since you want to test the non-default profile, you can open `about:profiles` and click the "open folder" button of the "root directory" section of the non-working profile, which will open the profile data folder.

Once in there check for a folder named "chrome", and see if the files you installed are inside along with a folder named "utils".

**Comment by tugl** [comment]
Yup this is what root directory\chrome\ folder look like inside:

![image](https://user-images.githubusercontent.com/61476585/97661121-e7deb880-1a49-11eb-9245-b5172957c46a.png)

**Comment by Izheil** [comment]
Everything seems to be right in there (except the root folder, which unless it comes from ShadowFox, it shouldn't be there).

Can you check if these files exist on Firefox installation folder?
* `C:\Program Files\Mozilla Firefox\config.js`
* `C:\Program Files\Mozilla Firefox\defaults\pref\config-pref.js`
(Change Mozilla Firefox for the Firefox version you are using if not using Firefox stable)

If those files exist, try clearing the startupCache folder of the problematic profile (go to `about:profiles` -> Open Local directory -> Access startupCache folder -> Close Firefox -> Delete all files in startupCache folder).

Also, can you try creating a new test profile and install any tabs below function there through the patcher to see if it applies on that one?

**Comment by tugl** [comment]
Okay, so I've removed root and Shadowfox leftovers

The config js files are there. I've cleared the startupCache too.

I created a 3rd now and only the first one gets themed. The 3rd profile has tabs below address bar:

![image](https://user-images.githubusercontent.com/61476585/97784851-d4317000-1b77-11eb-94f2-785b31ef9af5.png)

**Comment by Izheil** [comment]
Hmm.... Well, the functions are being loaded correctly, so it's just userChrome.css and userContent.css that aren't being loaded on the second profile...
userChrome could be loaded as a .as.css file, but userContent could not, so we can't do a workaround.

It seems like Firefox isn't recognizing the preference to load them in about:config, so try disabling `toolkit.legacyUserProfileCustomizations.stylesheets` (set it as false on the second profile), restart firefox, and then set it back to true. In the next restart of Firefox it should get recognized correctly.

If it still doesn't work, you can try forcing the preference using creating a file named `user.js` using notepad inside your profile (outside the chrome folder) with the code:

``` Javascript
// Force use of userChrome and userContent
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
```

This file doesn't exist by default, so if you already have it, it might be the culprit of the preference getting locked (and you should then change the value of that preference in that file to "true").

**Comment by tugl** [comment]
> ```js
> user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
> ```

This worked. Thanks!
