### ISSUE TITLE
Patcher fails if running as root user instead of regular user on Fedora 32 Server

### ISSUE THREAD

**Issue by candelab** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#96]
**Describe the bug**
ELF file will not execute under root login - Fedora 32 Server

**To Reproduce**
Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev3.elf

[root@localhost Downloads]# ./Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev3.elf
Traceback (most recent call last):
  File "Builder.py", line 42, in <module>
TypeError: getpwnam() argument must be str, not None
[4108] Failed to execute script Builder
[root@localhost Downloads]# 

**Expected behavior**
The ELF has to be run as a regular user. workaround is install the patch as a regular user, then manually copy the "chrome" directory from the regular user's ~/.mozilla/firefox/*release directory to /root/.mozilla/firefox/*release directory. Thanks for the fantastic app!

**Screenshots**

**Desktop (please complete the following information):**
Fedora Server 33 with Workstation 33 GUI

**Additional information**
Any information that could be relevant to fix the issue faster, such as:
 - You are using custom code that isn't in the default version contained in the repository.
 - Steps you followed to try to fix the issue on your own, if any.

**Comment by candelab** [comment]
> A clear and concise description of what you expected to happen. Not needed forThe elf has to be run as a regular user. workaround is install the patch as a regular user, then manually copy the "chrome" directory from the regular user's ~/.mozilla/firefox/*release directory to /root/.mozilla/firefox/*release directory. Thanks for the fantastic app!

**Comment by Izheil** [comment]
The installer tries to install it under your regular user, since that's how it's Firefox expected to be used. It needs root privileges since it needs to copy some files into Firefox installation folder.

If you are using Firefox as a root instead of a regular users for whichever reason, you will have to install it manually following the method from the [JS Loader](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader) folder in the repo, or as you said, copying the files that would be otherwise copied to your regular user firefox profile folder to the root one.

The installer is expected to be ran from a regular user (that is a root), where you will be asked for root permission, since that's the expected way of handling root actions on Linux, and the expected way of running Firefox.

**Comment by Izheil** [comment]
Should be fixed now on [rev4](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/download/FF83/Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev4.elf) of the Linux releases.
