### ISSUE TITLE
[REQUEST] MEGA Addon Support

### ISSUE THREAD

**Issue by Marcehs** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#97]
I just recently found Quantum Nox for Firefox and managed to get it successfully working on the recently released Waterfox G3.  I would be so grateful if a dark theme would be created for the MEGA cloud addon/extension.  Thank you for all the hard work on Quantum Nox!

link to page to dl the extension
https://mega.nz/extensions

**Comment by Izheil** [comment]
Sorry for the late reply, I've been busy these past days and haven't had much time to do anything.
Anyway! I'll start working on theming that extension when I have some time (starting on december probably). 
For what I see the layout is the same as the regular mega page, except it handles the downloads locally in the addon?

**Comment by Marcehs** [comment]
Oh, it's no problem at all.  As you said, you've been busy!
I was using a Stylus theme before I tried the extension.  Yes it does handle things locally through the browser and gets you to Mega super fast!

**Comment by Marcehs** [comment]
So, I posted a request for a dark theme here first but then found the Mega Subreddit and posted a request there for a dark theme and they actually replied stating that a dark theme will be coming soon!  So I appreciate the reply but you can probably go ahead and close this issue.

**Comment by Izheil** [comment]
Ah, alright, thanks for telling me!
While you wait for them to theme it you can always apply the Stylus theme you had for mega, since the page seems to be pretty much the same (unless they changed the selectors in the extension, it should still apply), you'll just need to change the url that it applies to in your userContent and add the theme in there (kinda like how the [addons.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/Full%20dark%20theme/addons.css) file does it).
