### ISSUE TITLE
[BUG] Can't start Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.9.elf

### ISSUE THREAD

**Issue by thomas-maeder** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#99]
**Describe the bug**
$ ./Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.9.elf 
[23587] Error loading Python lib '/tmp/_MEIznhXZF/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/_MEIznhXZF/libpython3.8.so.1.0)

2.32 seems a bit much to ask for.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional information**
$ ls -l /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 Aug 17 22:02 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.31.so

**Comment by Izheil** [comment]
[Check that your system is up to date](https://forum.manjaro.org/t/chromium-wont-open-says-glibc-2-32-not-found/23603/5), since [2.32 is the lastest version](https://launchpad.net/ubuntu/+source/glibc/).

The file was compiled from Kubuntu 20.04 which I had to reinstall on november, which is why it's asking for such high dependency.

Either way, update system-wide, or update the dependency:

```
sudo apt-get update
sudo apt-get install libc6
```

**Comment by gcbirzan** [comment]
This is not true. 20.04 has (as the link you provided says) 2.31. Are you sure it's 20.04 that you used to compile? https://packages.ubuntu.com/focal/libc6 also agrees with this.

**Comment by Izheil** [comment]
You are right, I used 20.10. Must have misremembered the minor verson.

![glibc version](https://user-images.githubusercontent.com/33794458/103564472-db019980-4ebe-11eb-8edd-b35060c7dc1b.png)

Still, the lastest version available is 2.32 (on The Groovy gorilla stable) as the link I sent stated, which was uploaded on 2020-09-20.

![2 32](https://user-images.githubusercontent.com/33794458/103564357-a7bf0a80-4ebe-11eb-9f42-e9de41e03179.png)

Either way, 20.04 uses Focal Fossa instead of Groovy, which I didn't know since I'm not that used to Linux upgrade systems, so I'll downgrade my VM to the LTS and reupload the installer again to prevent future problems with dependencies like this one.
I'll update this once I finish reinstalling and reuploading the installer.

**Comment by Izheil** [comment]
I downgraded to 20.04 and recompiled the binary, so [1.7.10](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF84) should now work with the LTS version of Ubuntu.
